In [12]:
import numpy as np
from control.matlab import *

## Question  1(c)

In [13]:
A1 = np.array([[0, 1], [0, 0]])
B1 = np.array([[0], [1]])
Q1 = np.eye(2)
R1 = 0.5

In [14]:
(K1, S1, E) = lqr(A1, B1, Q1, R1)
print("The optimal control matrix; K = " + str(K1)+ "\n")
print("S = " + str(S1))

The optimal control matrix; K = [[1.41421356 2.19736823]]

S = [[1.55377397 0.70710678]
 [0.70710678 1.09868411]]


## Question  2(a)

In [19]:
m_c = 0.2
m_p = 0.5
l = 0.5
g = 9.80364

In [23]:
A2 = np.array([[0, 0,1,0], [0, 0,0,1], [0,(m_p*g)/m_c,0,0],[0, ((m_c+m_p)*g)/(m_c*l),0,0] ])
B2 = np.array([[0], [0],[1/m_c],[1/(m_c*l)]])
Q2 = np.array([[1/20, 0,0,0], [0, 0.5*m_p*g*l,0,0], [0,0,0.5*(m_c + m_p),m_p*l],[0, 0,m_p*l,0.5*m_p*(l**2)] ])
R2 = 0.1* np.eye(1)

In [24]:
(K2, S2, E) = lqr(A2, B2, Q2, R2)
print("The optimal control matrix; K = " + str(K2)+ "\n")
print("S = " + str(S2))

The optimal control matrix; K = [[-0.70710678 24.04259064 -2.44505391  4.17850521]]

S = [[ 0.17289142 -0.29546494  0.12391443 -0.06902828]
 [-0.29546494  4.98641143 -1.20263877  0.84174529]
 [ 0.12391443 -1.20263877  0.39833655 -0.22361881]
 [-0.06902828  0.84174529 -0.22361881  0.15359446]]


 Verification that the solution the LQR function above outputs satisfies the equation derived in question 1 part (b)

In [25]:
Q2 + S2@A2 + (A2.T)@S2 - S2@B2@(np.linalg.inv(R2))@(B2.T)@S2

matrix([[-2.15799600e-15, -3.55271368e-15, -1.94289029e-15,
         -9.82547377e-15],
        [-4.21884749e-15,  2.13162821e-13, -4.61852778e-14,
          3.01980663e-14],
        [-1.97064587e-15, -4.70734562e-14,  1.22124533e-14,
         -9.32587341e-15],
        [-9.88098492e-15,  3.55271368e-14, -9.54791801e-15,
          4.66293670e-15]])